services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ticket-booking-network

  fake-services:
    build:
      context: ./fake-services-nodejs
      dockerfile: Dockerfile
    container_name: fake-services
    ports:
      - "3000:3000"
    environment:
      ZEEBE_ADDRESS: e942dd69-310c-4d3c-bae4-a9fd182f5235.lhr-1.zeebe.camunda.io:443
      ZEEBE_CLIENT_ID: h7vfi9gVg2S_-pdwuQnWPRPVcNethogN
      ZEEBE_CLIENT_SECRET: ihGYnq-unAEcYxriaIa7xUze0m1nUqZ~.0GJnNp4O1U.Ro2ZhIp93qFNR6fntFi1
      ZEEBE_AUTHORIZATION_SERVER_URL: https://login.cloud.camunda.io/oauth/token
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ticket-booking-network
    restart: unless-stopped

  booking-service:
    build:
      context: ./booking-service-java
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "8080:8080"
    environment:
      ZEEBE_CLIENT_CLOUD_REGION: lhr-1
      ZEEBE_CLIENT_CLOUD_CLUSTERID: e942dd69-310c-4d3c-bae4-a9fd182f5235
      ZEEBE_CLIENT_CLOUD_CLIENTID: h7vfi9gVg2S_-pdwuQnWPRPVcNethogN
      ZEEBE_CLIENT_CLOUD_CLIENTSECRET: ihGYnq-unAEcYxriaIa7xUze0m1nUqZ~.0GJnNp4O1U.Ro2ZhIp93qFNR6fntFi1
    depends_on:
      rabbitmq:
        condition: service_healthy
      fake-services:
        condition: service_started
    networks:
      - ticket-booking-network
    restart: unless-stopped

networks:
  ticket-booking-network:
    driver: bridge
