zeebe.client.cloud.region = lhr-1
zeebe.client.cloud.clusterId = e942dd69-310c-4d3c-bae4-a9fd182f5235
zeebe.client.cloud.clientId = h7vfi9gVg2S_-pdwuQnWPRPVcNethogN
zeebe.client.cloud.clientSecret = ihGYnq-unAEcYxriaIa7xUze0m1nUqZ~.0GJnNp4O1U.Ro2ZhIp93qFNR6fntFi1

spring.rabbitmq.host = rabbitmq
spring.rabbitmq.port = 5672
spring.rabbitmq.username = guest
spring.rabbitmq.password = guest

ticketbooking.payment.endpoint = http://fake-services:3000
