zeebe.client.cloud.region = ${ZEEBE_CLIENT_CLOUD_REGION}
zeebe.client.cloud.clusterId = ${ZEEBE_CLIENT_CLOUD_CLUSTERID}
zeebe.client.cloud.clientId = ${ZEEBE_CLIENT_CLOUD_CLIENTID}
zeebe.client.cloud.clientSecret = ${ZEEBE_CLIENT_CLOUD_CLIENTSECRET}

spring.rabbitmq.host = ${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port = ${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username = ${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password = ${SPRING_RABBITMQ_PASSWORD}

ticketbooking.payment.endpoint = http://fake-services:3000
